config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:'events#index'

  devise_for :users
  
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :checkouts, only: [:new, :create]
    resources :attendances, only: [:index]
    resources :event_images, only: [:create]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :profile_images, only: [:create]
  end
  
  namespace :admin do
    root to:"admin#index"
    resources :users, :events
    resources :event_submissions, only: [:index, :show, :update]
  end
  
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :attendees, foreign_key:'user_id', through: :attendances, class_name: "User"
  has_one_attached :avatar

  belongs_to :admin, class_name: "User"
  has_one_attached :event_image

  validate :check_date_is_not_past, :duration_multiple_5

  validates :start_date,
    presence: true
  
  validates :duration,
    presence: true,
    numericality: { only_integer: true, greater_than: 0 }

  validates :title,
    presence: true,
    length: { minimum: 5, maximum: 140 }

  validates :description,
    presence: true,
    length: { minimum: 20, maximum: 1000 }

  validates :price,
  presence: true,
  numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 1000 }

  validates :location, :avatar,
  presence: true

  def check_date_is_not_past
    if start_date <= Time.now
      errors.add(:start_date, "La start_date doit être dans le futur.")
    end
  end

  def duration_multiple_5
    if duration % 5 !=0
      errors.add(:duration, "La durée doit être un multiple de 5.")
    end
  end

  def calc_end_date
    self.start_date + self.duration*60
  end

end

app/controllers/admin/events_controller.rb
module Admin

  class EventsController < ApplicationController
    before_action :check_if_admin

    def index
      @all_events = Event.all
      # @user_to_add = User.new
    end

    def new
      @event_to_add = Event.new
    end

    def create
      puts "#"*100
      puts "params.inspect : #{params.inspect}"
      puts "#"*100
      
      event_to_create = Event.new(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], admin: current_user, validated: nil)

        if event_to_create.save
          flash.notice = "Évènement crée. En cours de validation."
          redirect_to admin_event_submissions_path
      else
          flash.alert = event_to_create.errors.full_messages
          redirect_to new_event_path
      end

    end

    def show

    end

    def edit
      @event_to_edit = Event.find(params[:id])
    end

    def update
      # event_to_update = Event.update(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], admin: current_user)
      event_to_update = Event.find(params[:id])

      # puts "#"*100
      # puts "AVANT LE IF"
      # puts "#"*100

      if event_to_update.update(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], admin: current_user)
      # puts "#"*100
      # puts "DANS LE IF"
      # puts "#"*100
        flash.notice = "Évènement mis à jour"
        redirect_to admin_events_path
      else
        # puts "#"*100
        # puts "DANS LE ELSE"
        # puts "#"*100
        flash.alert = event_to_update.errors.full_messages
        redirect_to edit_admin_event_path(event_to_update.id)
   end

    # puts "#"*100
    # puts "APRES LE IF"
    # puts "#"*100
  end

    def destroy
      event_to_destroy = Event.find(params[:id])
      admin_id = event_to_destroy.admin.id
      flash.notice = "fonction désactivée pour l'instant"
      # event_to_destroy.destroy
      redirect_to admin_events_path
    end

    private
    
    def check_if_admin

      unless current_user && current_user.is_app_admin
        flash.alert = "accès non aurotisé"
        redirect_to root_path
      end
      
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :authenticate_user!, only: [:new, :create]
before_action :authorize_edit_access, only: [:edit, :update, :destroy]
before_action :validation_status, only: [:show]

  def index
    @all_events = Event.all.where(validated: true)

    # Un évènement aléatoire à afficher sur la page d'accueil
    @random_event = Event.find(rand(Event.first.id..Event.last.id)) 
  end

  def show
    @event_to_show = Event.find(params[:id])
    @watcher_is_admin = is_watcher_admin?(current_user) # appel d'une méthode définie dans application_controller.rb
    @watcher_is_attendee = is_watcher_attendee?(current_user)
    puts "#"*100
    if current_user
      puts "current_user existe : #{current_user}"
    end
    if !current_user
      puts "current_user existe ? : #{current_user}" 
    end
    # puts "current _user.id : #{current_user.id}"
    puts "#"*100
  end

  def new
    @event_to_create = Event.new
  end

  def create
    event_to_create = Event.new(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], admin: current_user, validated: nil)

    if event_to_create.save
      flash.notice = "Évènement crée. En cours de validation."
      redirect_to root_path
   else
      flash.alert = event_to_create.errors.full_messages
      redirect_to new_event_path
   end
  end

  def edit
    @event_to_edit = Event.find(params[:id])
  end

  def update
    # event_to_update = Event.update(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], admin: current_user)
    event_to_update = Event.find(params[:id])

    # puts "#"*100
    # puts "AVANT LE IF"
    # puts "#"*100

    if event_to_update.update(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location], admin: current_user)
    # puts "#"*100
    # puts "DANS LE IF"
    # puts "#"*100
      flash.notice = "Évènement mis à jour"
      redirect_to event_path(event_to_update.id)
    else
      # puts "#"*100
      # puts "DANS LE ELSE"
      # puts "#"*100
      flash.alert = event_to_update.errors.full_messages
      redirect_to edit_event_path(event_to_update.id)
   end

    # puts "#"*100
    # puts "APRES LE IF"
    # puts "#"*100
  end

  def destroy
    event_to_destroy = Event.find(params[:id])
    admin_id = event_to_destroy.admin.id
    event_to_destroy.destroy
    redirect_to user_path(admin_id)
  end

  private

  def authorize_edit_access
    unless current_user == Event.find(params[:id]).admin
      flash.alert = "Accès non autorisé."
      redirect_to event_path(Event.find(params[:id]))
    end
  end

  def validation_status
    event = Event.find(params[:id])
    unless event.validated == true
      flash.alert = "Impossible : validation NIL ou FALSE."
      redirect_to root_path
    end
  end

end

app/views/admin/events/edit.html.erb
<main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Modification de l'event [ADMIN]</h1>

          <p><a class="btn btn-info btn-lg pe-none" href="#" role="button">Attire le moooonde entier ...</a></p>
        </div>
      </div>

      <div class="container mt-5  ">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-12">

            <h3>Quels sont les détails de ton event ?</h3>
              <%= form_tag url_for(action: 'update'), method: "patch" do %>
                <div class="row">

                  <div class="col-sm-4">
                    <h5><%= label_tag 'Date' %></h5> <!-- Le code plante en cas d'absence de saisie, voir pour forcer une value par défaut -->
                    <%= datetime_local_field_tag 'start_date', @event_to_edit.start_date, class: "form-control" %>

                    <h5><%= label_tag 'Durée (en min)' %></h5>
                    <%= number_field_tag 'duration', @event_to_edit.duration, class: "form-control" %>

                    <h5><%= label_tag 'Titre' %></h5>
                    <%= text_field_tag 'title', @event_to_edit.title, class: "form-control" %>

                  </div>

                  <div class="col-sm-4">
                  <h5><%= label_tag 'Description' %></h5>
                  <%= text_area_tag 'description', @event_to_edit.description, class: "form-control" %>

                  <h5><%= label_tag 'Prix' %></h5>
                  <%= number_field_tag 'price', @event_to_edit.price, class: "form-control" %>

                  <h5><%= label_tag 'Lieu' %></h5>
                  <%= text_field_tag 'location', @event_to_edit.location, class: "form-control" %>
                  </div>


                  <div class="col-sm-4 mt-5">
                    <%= submit_tag "OK" %>
                  </div>

                </div>
              <% end %>
          </div>
          
        </div>

        <hr>

      </div> <!-- /container -->

    </main>

    <%= button_to "SUPPRIMER", @event_to_edit, method: :delete, class:"btn btn-danger rounded " %>

  <h1>Ajouter une photo</h1>
    <%= form_tag event_event_images_path(@event_to_edit), multipart: true do %>
      <%= file_field_tag "event_image" %>
    <%= submit_tag "OK" %>
    <% end %>

app/views/admin/events/index.html.erb
<h1>ADMIN/EVENTS_CONTROLLER#INDEX</h1>

GESTION DES EVENTS

<h2><%= link_to "Ajouter un Event", new_admin_event_path, class: "btn btn-primary" %></h2>
Liste de tous les events :
<ul>
  <% @all_events.order(id: "asc").each do |event| %>
    <li>
      <%= event.inspect %>
      <br/><%= link_to "EDIT", edit_admin_event_path(event.id), class: "btn btn-warning" %>
      <br/><%= button_to "SUPPR", admin_event_path(event.id), method: :delete, class: "btn btn-danger" %>
    </li>
  <% end %>
</ul>



 

app/views/admin/events/new.html.erb
<main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Crée ton event ! [ADMIN]</h1>

          <p><a class="btn btn-info btn-lg pe-none" href="#" role="button">Attire le moooonde entier ...</a></p>
        </div>
      </div>

      <div class="container mt-5  ">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-12">

            <h3>Quels sont les détails de ton event ?</h3>
              <%= form_tag url_for(action: 'create'), method: "post" do %>
                <div class="row">

                  <div class="col-sm-4">
                    <h5><%= label_tag 'Date' %></h5> <!-- Le code plante en cas d'absence de saisie, voir pour forcer une value par défaut -->
                    <%= datetime_local_field_tag 'start_date', @event_to_add.start_date, class: "form-control" %>

                    <h5><%= label_tag 'Durée (en min)' %></h5>
                    <%= number_field_tag 'duration', @event_to_add.duration, class: "form-control", value: 60 %>

                    <h5><%= label_tag 'Titre' %></h5>
                    <%= text_field_tag 'title', @event_to_add.title, class: "form-control" %>

                  </div>

                  <div class="col-sm-4">
                  <h5><%= label_tag 'Description' %></h5>
                  <%= text_area_tag 'description', @event_to_add.description, class: "form-control" %>

                  <h5><%= label_tag 'Prix' %></h5>
                  <%= number_field_tag 'price', @event_to_add.price, class: "form-control" %>

                  <h5><%= label_tag 'Lieu' %></h5>
                  <%= text_field_tag 'location', @event_to_add.location, class: "form-control" %>
                  </div>


                  <div class="col-sm-4 mt-5">
                    <%= submit_tag "OK" %>
                  </div>

                </div>
              <% end %>
          </div>
          
        </div>

        <hr>

      </div> <!-- /container -->

    </main>