config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:'events#index'

  devise_for :users
  
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :checkouts, only: [:new, :create]
    resources :attendances, only: [:index]
    resources :event_images, only: [:create]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :profile_images, only: [:create]
  end
  
  namespace :admin do
    root to:"admin#index"
    resources :users, :events
    resources :event_submissions, only: [:index, :show, :update]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :attended_events, foreign_key: 'attendee_id', class_name: "Attendance"
  has_many :administrated_events, foreign_key: 'admin_id', class_name: "Event"

  has_one_attached :profile_image

    
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/admin/users_controller.rb
module Admin

  class UsersController < ApplicationController
    before_action :check_if_admin

    def index
      @all_users = User.all
      # @user_to_add = User.new
    end

    def new
      @user_to_add = User.new
    end

    def create
      puts "#"*100
      puts "params.inspect : #{params.inspect}"
      puts "#"*100
      
      if params[:is_app_admin] == "1"
        access_level = true
      elsif params[:is_app_admin] == "0"  
        access_level = false
      end

      user_to_add = User.new(email: params[:email], first_name: params[:first_name], last_name: params[:last_name], description:params[:description], password: params[:password], description: params[:description], is_app_admin: access_level)


      
      if user_to_add.save
        flash.notice = "User crée."
        redirect_to admin_users_path
      else
        flash.alert = user_to_add.errors.full_messages
        redirect_to new_admin_user_path
      end

    end

    def show

    end

    def edit
      @user_to_edit = User.find(params[:id])
    end

    def update
      # puts "#"*100
      # puts "On est dans le USER#UPDATE"
      # puts "params.inspect : #{params.inspect}"
      # puts "#"*100
      if params[:is_app_admin] == "1"
        access_level = true
      elsif params[:is_app_admin] == "0"  
        access_level = false
      end

      user_to_update = User.find(params[:id])

      if user_to_update.update(email: params[:email], first_name: params[:first_name], last_name: params[:last_name], description:params[:description], password: params[:password], description: params[:description], is_app_admin: access_level)
        flash.notice = "Informations mises à jour."
        redirect_to admin_users_path
      else
        flash.alert = user_to_update.errors.full_messages
        redirect_to edit_admin_user_path(user_to_update.id)
      end
    end

    def destroy
      @user_to_destroy = User.find(params[:id])
      # puts "#"*100
      # puts "@user_to_destroy est #{@user_to_destroy.id}"
      # puts "#"*100
      flash.notice = "Fonction désactivée pour l'instant."
      # @user_to_destroy.destroy
      redirect_to admin_users_path
    end

    private
    
    def check_if_admin

      unless current_user && current_user.is_app_admin
        flash.alert = "accès non aurotisé"
        redirect_to root_path
      end
      
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :is_profile_owner?, only: [:show, :edit, :update]

  def show
    @user_to_show = User.find(params[:id])
  end

  def edit
    @user_to_edit = User.find(params[:id])
  end

  def update
    user_to_update = User.find(params[:id])

    if user_to_update.update(first_name: params[:first_name], last_name: params[:last_name], description:params[:description])
      flash.notice = "Informations mises à jour."
      redirect_to user_path(user_to_update.id)
   else
      flash.alert = user_to_update.errors.full_messages
      redirect_to new_event_path
   end

  end

private

  def is_profile_owner?
    owner = User.find(params[:id])
    unless owner == current_user
      flash.alert = "Accès non autorisé."
      redirect_to root_path
    end
  end

end

app/views/users/edit.html.erb
<main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Modifie tes infos</h1>

          <p><a class="btn btn-info btn-lg pe-none" href="#" role="button">Dis nous tout !</a></p>
        </div>
      </div>

      <div class="container mt-5  ">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-12">

            <h3>Tes infos</h3>
              <%= form_tag url_for(action: 'update'), method: "patch" do %>
                <div class="row">

                  <div class="col-sm-4">
                    <h5><%= label_tag 'Prénom' %></h5>
                    <%= text_field_tag 'first_name', @user_to_edit.first_name, class: "form-control", value: @user_to_edit.first_name  %>

                    <h5><%= label_tag 'Nom' %></h5>
                    <%= text_field_tag 'last_name', @user_to_edit.last_name, class: "form-control", value: @user_to_edit.last_name  %>
                  </div>

                  <div class="col-sm-4">
                    <h5><%= label_tag 'Ta description' %></h5>
                    <%= text_area_tag 'description', @user_to_edit.description, class: "form-control", value: @user_to_edit.description  %>
                    <br/>
                    <%= submit_tag "OK" %>
                  </div>

                </div>
              <% end %>
          </div>
          
        </div>

        <hr>

      </div> <!-- /container -->

    </main>

  <h1>Ajouter une photo</h1>
    <%= form_tag user_profile_images_path(@user_to_edit), multipart: true do %>
      <%= file_field_tag "profile_image" %>
    <%= submit_tag "OK" %>
    <% end %>

app/views/users/show.html.erb
<main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Ton profil</h1>
          <p><a class="btn btn-success btn-lg pe-none" href="#" role="button">de Jetsetter</a></p>
        </div>
      </div>

      <div class="container mt-5">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Toi</h2>
              <ul>
                <li>Prénom : <%= @user_to_show.first_name %></li>
                <li>Nom :  <%= @user_to_show.last_name %></li>
                <li>Description : <%= @user_to_show.description %></li>
                <li>Email :  <%= @user_to_show.email %></li>
              </ul>
          </div>
          <div class="col-md-4">
            <h2>Tes events crées</h2>
              <ul>
                <% @user_to_show.administrated_events.each do |event| %>
                <li>Titre : <%= event.title %> <%= link_to "voir", event_path(event.id) %></li>
                <% end %>
              </ul>
          </div>
          <div class="col-md-4">
            <h2>Tes paramètres</h2>
              <%= link_to "Modifier tes identifiants", edit_user_registration_path(@user_to_show.id), class: "btn btn-warning" %>
              <%= link_to "Modifier tes infos", edit_user_path(@user_to_show.id), class: "btn btn-secondary" %>
          </div>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>

<h3>Photo</h3>
<% if @user_to_show.profile_image.attached? %>
  <%= image_tag @user_to_show.profile_image, alt: 'profile_image' %>
<% else %>
  <p>=== pas encore d'image ===</p>
<% end %>