config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:'events#index'

  devise_for :users
  
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :checkouts, only: [:new, :create]
    resources :attendances, only: [:index]
    resources :event_images, only: [:create]
  end

  resources :users, only: [:show, :edit, :update] do
    resources :profile_images, only: [:create]
  end
  
  namespace :admin do
    root to:"admin#index"
    resources :users, :events
    resources :event_submissions, only: [:index, :show, :update]
  end
  
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
before_action :authenticate_user!, only:  [:new, :create]
  def new
    @event_to_pay = Event.find(params[:event_id])
    @amount = @event_to_pay.price
    # @event = Event.find(params[:id])
    # @amount = @event.price
  end

  def create

    puts "#"*100
    puts "params.inspect : #{params.inspect}"
    puts "#"*100

    # @user = current_user
    @event = Event.find(params[:event_id])
    

    # Before the rescue, at the beginning of the method
    @stripe_amount = @event.price*100
    begin
      customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
      })
      charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @stripe_amount,
      description: "Achat d'un produit",
      currency: 'eur',
      })
    puts "#"*100
    puts "PAIEMENT ok."
    puts "Stripe::Customer : #{customer.id}."
    puts "Stripe::Customer : #{customer.class}."
    puts "#"*100
      
      Attendance.create(strip_customer_id: customer.id ,event: @event, attendee: current_user) 
      flash.notice = "Ta participation est enregsitrée. (faire une mail ?)"
      redirect_to event_path(@event.id)    

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to event_path(@event.id)
    puts "#"*100
    puts "RESCUE ok."
    puts "#"*100
    end

    puts "#"*100
    puts "APRES TOUT."
    puts "#"*100
    # After the rescue, if the payment succeeded
  end

  # # Utilisation d'une méthode/route #show pour obtenir une URL dynamique pour la page d'affichage du paiement.
  # # De cette façon, on peut récupérer l'id de l'event via params. Ce qui n'aurait pas été le cas avec la méthode #new.
  # def show 
  #   @event_to_pay = Event.find(params[:id])
  #   @amount = @event_to_pay.price
  # end

end

app/views/checkouts/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/checkouts/new.html.erb
<h1> PAGE DE CHECKOUT</h1>

PAIEMENT DE L'EVENT <%= @event_to_pay.title %>

<%= form_tag event_checkouts_path(@event_to_pay.id) do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <label class="amount">
    <span>Amount: <%= @event_to_pay.price %></span>
  </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Achat d'un produit"
    data-amount = <%= @stripe_amount %>
    data-currency = "eur"
    data-locale="auto">
</script>
<% end %>

app/views/checkouts/show.html.erb
A SUPPRIMER